Remove explicit optimization
O3 is the default setting and ic-wasm v0.5.0 doesn't seem to recognize
the --optimize flag. Running with this flag results in the following
error:

```
Optimize with ic-wasm
error: unexpected argument '--optimize' found

Usage: ic-wasm <INPUT> shrink [OPTIONS]

For more information, try '--help'.
```

Therefore, leveraging the implicit default optimization seems like the
best solution for now.